def comment_string(script_name, timestamp):
    return \
fr"""// auto-generated by {script_name} at {timestamp}
// Don't modify this file manually!!!"""


def h_file_string(comment_string, class_name, method_name):
    return \
fr"""{comment_string}

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface {class_name} : NSObject
+ (NSDictionary *){method_name};
@end

NS_ASSUME_NONNULL_END
"""


def m_file_string(comment_string, class_name, method_name, literal_string):
    return \
fr"""{comment_string}

#import "{class_name}.h"

@implementation {class_name}

+ (NSDictionary *){method_name} {{
    return 
{literal_string};
}}

@end

"""
