// auto-generated by /Users/wesley_chen/GitHub_Projects/HelloPython/python_task/01_generate_file_from_template/generate_file_from_template.py at 2020-02-23 17:41:30.330746
// Don't modify this file manually!!!

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface PresetData1 : NSObject
+ (NSDictionary *)presetData;
@end

NS_ASSUME_NONNULL_END
