// auto-generated by /Users/wesley_chen/GitHub_Projects/HelloPython/python_task/01_generate_file_from_template/generate_file_from_template.py at 2020-02-23 17:41:30.330746
// Don't modify this file manually!!!

#import "PresetData1.h"

@implementation PresetData1

+ (NSDictionary *)presetData {
    return 
@{
  @"73" : @{
    @"env" : @"public",
    @"id" : @"73",
    @"style" : @"left",
    @"namespace" : @"message",
    @"ext" : @"{\"url\":\"https://domain/app/path/to/pages/index?h=native\"}",
    @"mappingId" : @"73",
    @"type" : @"component",
    @"updateTime" : @"1580886159460"
  },
  @"74" : @{
    @"env" : @"public",
    @"id" : @"74",
    @"style" : @"right",
    @"namespace" : @"message",
    @"ext" : @"",
    @"mappingId" : @"74",
    @"type" : @"component",
    @"updateTime" : @"1581487578770"
  }
};
}

@end

