// auto-generated by /Users/wesley_chen/GitHub_Projects/HelloPython/python_task/01_generate_file_from_template/generate_file_from_template.py at 2020-02-23 17:43:26.721290
// Don't modify this file manually!!!

#import "PresetData2.h"

@implementation PresetData2

+ (NSDictionary *)presetData {
    return 
@{
  @"prefix_136" : @{
    @"data" : @"{\"tplUrl\":\"https://path/to/main.js\",\"timestamp\":\"800\"}",
    @"env" : @"public",
    @"group" : @"default",
    @"id" : @"136",
    @"namespace" : @"message",
    @"rawDict" : @{
      @"data" : @"{\"tplUrl\":\"https://path/to/main.js\",\"timestamp\":\"800\"}",
      @"env" : @"public",
      @"group" : @"default",
      @"id" : @"136",
      @"namespace" : @"message",
      @"type" : @"1",
      @"updateTime" : @"1535529241138",
      @"version" : @"1"
    },
    @"type" : @(1),
    @"updateTime" : @"1535529241138",
    @"version" : @(1)
  },
  @"prefix_2" : @{
    @"data" : @"{\"json\":\"{\\\"name\\\":\\\"some_name\\\",\\\"version\\\":\\\"2\\\",\\\"url\\\":\\\"https://path/index.zip\\\"}\",\"timestamp\":\"10\"}",
    @"env" : @"public",
    @"group" : @"base",
    @"id" : @"2",
    @"namespace" : @"message",
    @"rawDict" : @{
      @"data" : @"{\"json\":\"{\\\"name\\\":\\\"some_name\\\",\\\"version\\\":\\\"2\\\",\\\"url\\\":\\\"https://path/index.zip\\\"}\",\"timestamp\":\"10\"}",
      @"env" : @"public",
      @"group" : @"base",
      @"id" : @"2",
      @"namespace" : @"message",
      @"type" : @"3",
      @"updateTime" : @"1581321820010",
      @"version" : @"8"
    },
    @"type" : @(3),
    @"updateTime" : @"1581321820010",
    @"version" : @(8)
  }
};
}

@end

